<a href="https://colab.research.google.com/github/AmirVahedix/DeepLearning/blob/main/tensorflow_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

# Data Structures

## 1. Zero Dimensional

In [2]:
a = tf.constant(0)
a

<tf.Tensor: shape=(), dtype=int32, numpy=0>

## 1. One Dimensonal

In [3]:
b = tf.constant([1, 2])
b

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

## Two Dimensional (Matrix)

In [4]:
c = tf.constant([[1, 2], [1, 2]])
c

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [1, 2]], dtype=int32)>

## Three Dimensional (Tensor)

In [5]:
d = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
d

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int32)>

# Operators

In [6]:
x = tf.constant([1, 2])
y = tf.constant([3, 4])

## 1. Summation

In [7]:
sum = tf.add(x, y)
sum.numpy()

array([4, 6], dtype=int32)

## 2. Subtract

In [8]:
sub = tf.subtract(x, y)
sub.numpy()

array([-2, -2], dtype=int32)

## 3. Multiplication

### Element Wise:

In [9]:
ew = tf.multiply(x, y)
ew.numpy()

array([3, 8], dtype=int32)

### Matrix Multiplication

In [10]:
x_1 = tf.constant([[1, 2], [3, 4]])
y_1 = tf.constant([[4, 5], [7, 8]])

mm = tf.matmul(x_1, y_1)
mm.numpy()

array([[18, 21],
       [40, 47]], dtype=int32)

## 4. Division

In [11]:
div = tf.divide(x, y)
div.numpy()

array([0.33333333, 0.5       ])

## 5. Square

In [31]:
a = tf.constant([[1, 2.0], [3, 4]])
tf.square(a)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

## 6. Square Root

In [34]:
from numpy import float32
tf.sqrt(tf.cast(a, dtype=float32))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.       , 1.4142135],
       [1.7320508, 2.       ]], dtype=float32)>

# Broadcasting

In [13]:
a = tf.constant([1, 2, 3])
b = tf.constant(4)

a * b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 4,  8, 12], dtype=int32)>

# Reshaping

In [16]:
a = tf.constant([1, 2, 3, 4, 5, 6])
a.shape

TensorShape([6])

In [17]:
b = tf.reshape(a, (2, 3))
b

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [18]:
tf.reshape(a, (2, 3, 1))

<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]], dtype=int32)>

In [19]:
tf.reshape(a, (3, 2, 1))

<tf.Tensor: shape=(3, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]]], dtype=int32)>

In [20]:
tf.reshape(a, (1, 2, 3))

<tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>

# Adding Dimensions

In [25]:
a = tf.constant([1, 2, 3, 4, 5, 6])
a

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>

In [26]:
tf.expand_dims(a, 0)

<tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[1, 2, 3, 4, 5, 6]], dtype=int32)>

In [28]:
tf.expand_dims(a, 1)

<tf.Tensor: shape=(6, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]], dtype=int32)>

In [29]:
tf.expand_dims(a, -1)

<tf.Tensor: shape=(6, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]], dtype=int32)>

# Min, Max, Mean, STD

In [35]:
a = tf.constant([[1, 2], [3, 4]])

## 1. Min

In [37]:
tf.reduce_min(a)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [38]:
tf.reduce_min(a, axis=None)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [39]:
tf.reduce_min(a, axis=0)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [40]:
tf.reduce_min(a, axis=1)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 3], dtype=int32)>

## 2. Max

In [41]:
tf.reduce_max(a)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [43]:
tf.reduce_max(a, axis=0)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4], dtype=int32)>

## 3. Mean

In [44]:
tf.reduce_mean(a)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [46]:
tf.reduce_mean(tf.cast(a, dtype=float32), axis=1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.5, 3.5], dtype=float32)>

## 4. Standard Deviation

In [49]:
tf.math.reduce_std(tf.cast(a, dtype=float32))

<tf.Tensor: shape=(), dtype=float32, numpy=1.1180339>

In [50]:
tf.math.reduce_std(tf.cast(a, dtype=float32), axis=1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.5, 0.5], dtype=float32)>

## 5. Sum

In [51]:
tf.reduce_sum(a)

<tf.Tensor: shape=(), dtype=int32, numpy=10>