<a href="https://colab.research.google.com/github/AmirVahedix/deep_learning/blob/main/tensorflow_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

# Data Structures

## 1. Zero Dimensional

In [ ]:
a = tf.constant(0)
a

<tf.Tensor: shape=(), dtype=int32, numpy=0>

## 1. One Dimensonal

In [ ]:
b = tf.constant([1, 2])
b

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

## Two Dimensional (Matrix)

In [ ]:
c = tf.constant([[1, 2], [1, 2]])
c

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [1, 2]], dtype=int32)>

## Three Dimensional (Tensor)

In [ ]:
d = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
d

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int32)>

# Operations

In [ ]:
x = tf.constant([1, 2])
y = tf.constant([3, 4])

## 1. Summation

In [ ]:
sum = tf.add(x, y)
sum.numpy()

array([4, 6], dtype=int32)

## 2. Subtract

In [ ]:
sub = tf.subtract(x, y)
sub.numpy()

array([-2, -2], dtype=int32)

## 3. Multiplication

### Element Wise:

In [ ]:
ew = tf.multiply(x, y)
ew.numpy()

array([3, 8], dtype=int32)

### Matrix Multiplication

In [ ]:
x_1 = tf.constant([[1, 2], [3, 4]])
y_1 = tf.constant([[4, 5], [7, 8]])

mm = tf.matmul(x_1, y_1)
mm.numpy()

array([[18, 21],
       [40, 47]], dtype=int32)

## Division

In [ ]:
div = tf.divide(x, y)
div.numpy()

array([0.33333333, 0.5       ])